version: '3'

services:
  server:
    depends_on:
      - mongo
    image: ra-server
    build:
      context: .
    ports:
      - ${HOST_PORT}:${SERVER_PORT}
    volumes:
      - ./:/app
    environment:
      MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: npm start
  mongo:
    image: mongo
    restart: always
    ports:
     - ${MONGODB_HOST_PORT}:${MONGODB_PORT}
    volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
 